# Generated by Django 5.1.7 on 2025-05-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_brand_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
