# Generated by Django 5.1.7 on 2025-05-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_myuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="last_prize",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="spin_chances",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
