# Generated by Django 5.1.7 on 2025-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_last_prize_myuser_spin_chances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='spin_chances',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
