services:
  django:
    image: django_team23
    container_name: django_team23
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  react:
    image: react_team23
    container_name: react_team23
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - 3000:3000
