# Generated by Django 5.1.9 on 2025-05-15 11:54

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keywords', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('voyage_embedding', django_mongodb_backend.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
    ]
