# Generated by Django 5.1.7 on 2025-05-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_chances', models.PositiveIntegerField(default=0, verbose_name='剩餘抽獎次數')),
                ('last_spin_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='上次抽獎結果')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spin_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者抽獎資料',
                'verbose_name_plural': '使用者抽獎資料',
            },
        ),
    ]
